/** Permanent (308) aliases. Each destination is a real page, not another alias. */
export const PUBLIC_AND_ADMIN_REDIRECTS: Array<{ source: string; destination: string; permanent: true }> = [
  { source: '/admin/manage-users', destination: '/admin/user-management', permanent: true },
  { source: '/capabilities', destination: '/features', permanent: true },
  { source: '/help-center', destination: '/help', permanent: true },
  { source: '/signup', destination: '/get-started', permanent: true },
  { source: '/auth/register', destination: '/get-started', permanent: true },
  { source: '/register/shop', destination: '/auth/register/shop', permanent: true },
  { source: '/pricing', destination: '/features', permanent: true },
  { source: '/register/success', destination: '/auth/thank-you', permanent: true },
  { source: '/register/canceled', destination: '/auth/thank-you', permanent: true },
  { source: '/admin/subscriptions', destination: '/admin/home', permanent: true },
  { source: '/auth/forgot', destination: '/auth/reset', permanent: true },
  { source: '/forgot-password', destination: '/auth/reset', permanent: true },
  { source: '/auth/forgot-password', destination: '/auth/reset', permanent: true },
  { source: '/reset-password', destination: '/auth/reset', permanent: true },
  { source: '/auth/reset-password', destination: '/auth/reset', permanent: true },
  { source: '/auth/password', destination: '/auth/reset', permanent: true },
  { source: '/privacy-policy', destination: '/privacy', permanent: true },
  { source: '/terms-of-service', destination: '/terms', permanent: true },
  { source: '/index', destination: '/', permanent: true },
];
